version: "3.3"
services:

  consul:
    image: consul:1.6.3
    command: ["consul","agent","-config-file=/config/consul-single-dc.hcl","-config-dir=/config"]
    volumes:
      - "./consul_config:/config"
    ports:
      - 8500:8500
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  expense-db-mysql:
    image: joatmon08/expense-db:mysql
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Testing!123
  expensedb_proxy_mysql:
    image: joatmon08/consul-envoy:1.6.3-1.11.1
    restart: always
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/expensedb-mysql.hcl
    volumes:
      - "./service_config:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "expense-db-mysql"]
    network_mode: "service:expense-db-mysql"

  jaeger:
    image: jaegertracing/all-in-one:1.13
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.10

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16